const transition=document.querySelector('.page-transition');
const word=document.querySelector('.transition-word');
const sub=document.querySelector('.transition-sub');
function split(el){if(!el)return;const text=el.textContent;el.textContent='';[...text].forEach((c,i)=>{const s=document.createElement('span');s.textContent=c===' '?'\u00a0':c;s.style.setProperty('--i',i);el.appendChild(s)})}
function details(){if(!transition)return;if(!transition.querySelector('.transition-noise')){const n=document.createElement('div');n.className='transition-noise';transition.appendChild(n)}if(!transition.querySelector('.transition-corner')){const a=document.createElement('div');a.className='transition-corner';transition.appendChild(a);const b=document.createElement('div');b.className='transition-corner right';transition.appendChild(b)}if(!transition.querySelector('.transition-mark')){const m=document.createElement('div');m.className='transition-mark';m.textContent='INK / MEMORY / 01';transition.appendChild(m)}split(word);split(sub)}
function play(label='studio',done){if(!transition){done?.();return}sub.textContent=label;split(sub);transition.classList.remove('is-done');transition.classList.remove('replay');void transition.offsetWidth;transition.classList.add('replay');setTimeout(()=>done?.(),720);setTimeout(()=>transition.classList.add('is-done'),1250)}
details();
window.addEventListener('load',()=>{play(document.body.dataset.section||'studio');setTimeout(()=>transition?.classList.add('is-done'),1450)});
document.querySelectorAll('[data-page]').forEach(link=>link.addEventListener('click',e=>{const href=link.getAttribute('href');if(!href)return;e.preventDefault();const label=link.dataset.page;play(label,()=>{window.location.href=href})}));
document.querySelector('[data-back]')?.addEventListener('click',e=>{e.preventDefault();play('studio',()=>window.location.href='index.html')});
document.querySelector('.tattoo-form')?.addEventListener('submit',e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.textContent='ЗАПРОС ПОЛУЧЕН ✓';b.disabled=true});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.dataset.section==='contacts')play('studio',()=>window.location.href='index.html')});